name: slay-the-bearboy

services:
  web:
    build:
      context: ../web
      dockerfile: ../docker/Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ../web:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=${PORT:-3000}
    command: sh -c 'npm install && npm run dev -- -p "${PORT:-3000}"'
